Changed XM Cloud deploy scrupt to bash format

diff --git a/.github/workflows/deploy_XM_Cloud.yml b/.github/workflows/deploy_XM_Cloud.yml
--- a/.github/workflows/deploy_XM_Cloud.yml
+++ b/.github/workflows/deploy_XM_Cloud.yml
@@ -52,17 +52,19 @@ jobs:
       run: dotnet sitecore cloud login --client-credentials --client-id ${{ secrets.XM_CLOUD_CLIENT_ID }} --client-secret ${{ secrets.XM_CLOUD_CLIENT_SECRET }}
     - name: Deploy the CM assets to XM Cloud
       run: |
-        $result = dotnet sitecore cloud deployment create --environment-id ${{ secrets.STAGING_XM_CLOUD_ENVIRONMENT_ID }} --upload --json | jq
-        Write-Host $result
-        if($result.IsTimedOut) {
-            Write-Error -Message "Operation Timed Out." -ErrorAction Stop
+        result = dotnet sitecore cloud deployment create --environment-id ${{ secrets.STAGING_XM_CLOUD_ENVIRONMENT_ID }} --upload --json | jq
+        echo $result
+        if $result.IsTimedOut
+        then
+            echo -Message "Operation Timed Out." -ErrorAction Stop
             exit -1
-        }
-        if(-not $result.IsCompleted) {
-            Write-Error -Message "Operation Failed." -ErrorAction Stop
+        fi  
+        if ! $result.IsCompleted
+        then
+            echo -Message "Operation Failed." -ErrorAction Stop
             exit -1
-        }
-        Write-Host "Deployment  Completed"
+        fi
+        echo "Deployment  Completed"
     - name: Authenticate default environment with CLI
       run: dotnet sitecore login --ref xmcloud --client-credentials true --client-id ${{ secrets.XM_CLOUD_CLIENT_ID }} --client-secret ${{ secrets.XM_CLOUD_CLIENT_SECRET }} --cm ${{ secrets.STAGING_XM_CLOUD_CM_URL }} --allow-write true
     - name: Publish content changes
@@ -84,17 +86,19 @@ jobs:
       run: dotnet sitecore cloud login --client-credentials --client-id ${{ secrets.XM_CLOUD_CLIENT_ID }} --client-secret ${{ secrets.XM_CLOUD_CLIENT_SECRET }}
     - name: Deploy the CM assets to XM Cloud
       run:  |
-        $result = dotnet sitecore cloud deployment create --environment-id ${{ secrets.PROD_ENVIRONMENT_ID }} --upload --json | jq
-        Write-Host $result
-        if($result.IsTimedOut) {
-            Write-Error -Message "Operation Timed Out." -ErrorAction Stop
+        result = dotnet sitecore cloud deployment create --environment-id ${{ secrets.PROD_ENVIRONMENT_ID }} --upload --json | jq
+        echo $result
+        if $result.IsTimedOut
+        then
+            echo -Message "Operation Timed Out." -ErrorAction Stop
             exit -1
-        }
-        if(-not $result.IsCompleted) {
-            Write-Error -Message "Operation Failed." -ErrorAction Stop
+        fi  
+        if ! $result.IsCompleted
+        then
+            echo -Message "Operation Failed." -ErrorAction Stop
             exit -1
-        }
-        Write-Host "Deployment  Completed"
+        fi
+        echo "Deployment  Completed"
     - name: Authenticate default environment with CLI
       run: dotnet sitecore login --ref xmcloud --client-credentials true --client-id ${{ secrets.XM_CLOUD_CLIENT_ID }} --client-secret ${{ secrets.XM_CLOUD_CLIENT_SECRET }} --cm ${{ secrets.PROD_XM_CLOUD_CM_URL }} --allow-write true
     - name: Publish content changes
