Removed sleep from prod xm cloud deploy

diff --git a/.github/workflows/deploy_XM_Cloud.yml b/.github/workflows/deploy_XM_Cloud.yml
--- a/.github/workflows/deploy_XM_Cloud.yml
+++ b/.github/workflows/deploy_XM_Cloud.yml
@@ -70,43 +70,40 @@ jobs:
     # - name: Authenticate default environment with CLI
     #   run: dotnet sitecore cloud environment connect -id ${{ secrets.STAGING_XM_CLOUD_ENVIRONMENT_ID }} --allow-write
     # - name: Publish content changes
-    #   run: |
-    #     dotnet sitecore publish --pt Edge -n Staging
+    #   run: dotnet sitecore publish --pt Edge -n Staging
 
-  # deploy-production:
-  #   name: Deploy the XM Cloud Production Site
-  #   if: github.ref == 'refs/heads/main'
-  #   needs: deploy-staging
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #   - uses: actions/checkout@v3
-  #   - uses: actions/setup-dotnet@v2
-  #     with:
-  #       dotnet-version: '6.0.x' 
-  #   - run: dotnet tool restore
-  #   - run: dotnet sitecore --help
-  #   - name: Authenticate CLI with XM Cloud
-  #     run: dotnet sitecore cloud login --client-credentials --client-id ${{ secrets.XM_CLOUD_CLIENT_ID }} --client-secret ${{ secrets.XM_CLOUD_CLIENT_SECRET }} --allow-write
-  #   - name: Deploy the CM assets to XM Cloud
-  #     run:  |
-  #       result=$(dotnet sitecore cloud deployment create --environment-id ${{ secrets.PROD_ENVIRONMENT_ID }} --upload --json)
-  #       echo $result
-  #       isTimedOut=$(echo $result | jq ' .IsTimedOut')
-  #       isCompleted=$(echo $result | jq ' .IsCompleted')
-  #       if [ $isTimedOut = true ]
-  #       then
-  #           echo "Operation Timed Out."
-  #           exit -1
-  #       fi  
-  #       if ! [ $isCompleted = true ]
-  #       then
-  #           echo "Operation Failed."
-  #           exit -1
-  #       fi
-  #       echo "Deployment  Completed - Waiting for Env to warmup"
-  #       sleep 3m
+  deploy-production:
+    name: Deploy the XM Cloud Production Site
+    if: github.ref == 'refs/heads/main'
+    needs: deploy-staging
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v3
+    - uses: actions/setup-dotnet@v2
+      with:
+        dotnet-version: '6.0.x' 
+    - run: dotnet tool restore
+    - run: dotnet sitecore --help
+    - name: Authenticate CLI with XM Cloud
+      run: dotnet sitecore cloud login --client-credentials --client-id ${{ secrets.XM_CLOUD_CLIENT_ID }} --client-secret ${{ secrets.XM_CLOUD_CLIENT_SECRET }} --allow-write
+    - name: Deploy the CM assets to XM Cloud
+      run:  |
+        result=$(dotnet sitecore cloud deployment create --environment-id ${{ secrets.PROD_ENVIRONMENT_ID }} --upload --json)
+        echo $result
+        isTimedOut=$(echo $result | jq ' .IsTimedOut')
+        isCompleted=$(echo $result | jq ' .IsCompleted')
+        if [ $isTimedOut = true ]
+        then
+            echo "Operation Timed Out."
+            exit -1
+        fi  
+        if ! [ $isCompleted = true ]
+        then
+            echo "Operation Failed."
+            exit -1
+        fi
+        echo "Deployment  Completed"
   #   - name: Authenticate default environment with CLI
-  #     #run: dotnet sitecore login --ref xmcloud --client-credentials true --client-id ${{ secrets.XM_CLOUD_CLIENT_ID }} --client-secret ${{ secrets.XM_CLOUD_CLIENT_SECRET }} --cm ${{ secrets.PROD_XM_CLOUD_CM_URL }} --allow-write true
   #     run: dotnet sitecore cloud environment connect -id ${{ secrets.PROD_ENVIRONMENT_ID }} --allow-write
   #   - name: Publish content changes
   #     run: dotnet sitecore publish --pt Edge -n Production
